package app.neuland.model;

public enum SportsCategory {
    BASKETBALL, FOOTBALL, CALISTHENICS, VOLLEYBALL,
    HANDBALL, BOULDERING, BADMINTON, TENNIS, SWIMMING, MARTIAL_ARTS, YOGA,
    DANCING, OTHER
}
