CREATE TABLE university_sports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus VARCHAR(50) NOT NULL,
    location VARCHAR(255) NOT NULL,
    weekday VARCHAR(50) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME,
    requires_registration BOOLEAN NOT NULL,
    invitation_link TEXT,
    e_mail VARCHAR(255),
    sports_category VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE university_sports_contents (
    university_sports_id BIGINT NOT NULL,
    language VARCHAR(50) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,

    PRIMARY KEY (university_sports_id, language),

    CONSTRAINT fk_university_sports_content
        FOREIGN KEY (university_sports_id)
            REFERENCES university_sports(id)
            ON DELETE CASCADE
);
