CREATE TABLE university_sports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_de VARCHAR(255) NOT NULL,
    description_de TEXT,
    title_en VARCHAR(255) NOT NULL,
    description_en TEXT,
    campus VARCHAR(50) NOT NULL,
    location VARCHAR(255) NOT NULL,
    weekday VARCHAR(50) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME,
    requires_registration BOOLEAN NOT NULL,
    invitation_link TEXT,
    e_mail VARCHAR(255),
    sports_category VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);