CREATE TABLE announcements (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               start_date_time TIMESTAMP WITH TIME ZONE NOT NULL,
                               end_date_time TIMESTAMP WITH TIME ZONE NOT NULL,
                               priority INTEGER NOT NULL,
                               url TEXT,
                               image_url TEXT
);

CREATE TABLE announcement_platforms (
                                        announcement_id BIGINT NOT NULL,
                                        platform VARCHAR(50) NOT NULL,

                                        PRIMARY KEY (announcement_id, platform),

                                        CONSTRAINT fk_announcement_platform
                                            FOREIGN KEY (announcement_id)
                                                REFERENCES announcements(id)
                                                ON DELETE CASCADE
);

CREATE TABLE announcement_user_kinds (
                                         announcement_id BIGINT NOT NULL,
                                         user_kind VARCHAR(50) NOT NULL,

                                         PRIMARY KEY (announcement_id, user_kind),

                                         CONSTRAINT fk_announcement_user_kind
                                             FOREIGN KEY (announcement_id)
                                                 REFERENCES announcements(id)
                                                 ON DELETE CASCADE
);

CREATE TABLE announcement_contents (
                                       announcement_id BIGINT NOT NULL,
                                       language VARCHAR(50) NOT NULL,
                                       title TEXT NOT NULL,
                                       description TEXT NOT NULL,

                                       PRIMARY KEY (announcement_id, language),

                                       CONSTRAINT fk_announcement_content
                                           FOREIGN KEY (announcement_id)
                                               REFERENCES announcements(id)
                                               ON DELETE CASCADE
);