CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT,
    operation VARCHAR(20) NOT NULL,
    name VARCHAR(255),
    user_id VARCHAR(255),
    occurred_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_audit_logs_occurred_at_id
    ON audit_logs (occurred_at DESC, id DESC);
